before_script:
  - sudo pip2.7 install --upgrade pip
  - sudo pip2.7 install --upgrade conan
  - rm -rf ~/.conan

geebee:
  script:
    - rm -rf build
    - mkdir -p build
    - cd build
    - conan install -s compiler=gcc -s compiler.libcxx=libstdc++11 ..
    - cmake ..
    - cmake --build .
    - ctest -V
